### ISSUE TITLE
which charting lib?

### ISSUE THREAD

**Issue by karussell** [graphhopper/measurement#1]
The only requirement are simple error bars

 * our current solution https://github.com/danvk/dygraphs
 * flot http://www.flotcharts.org/flot/examples/series-errorbars/index.html
 * plotly.js https://plot.ly/javascript/error-bars/ (my preferred thing as it is nice that one can zoom in+out and pan and community seems to be very active)
 * JS charts http://www.ejschart.com/examples.php
 * jqplot http://www.jqplot.com/examples/bandedLine.php

**Comment by karussell** [comment]
for now plotly.js

**Comment by oblonski** [comment]
plotly looks nice.
